title: Rain Blog
tagline: Every dawn I dream through the void and its serene desolate fairytales
description: Every dawn I dream through the void and its serene desolate fairytales
url: https://echometerain.github.io
author:
  name: echometerain
  picture: /assets/img/echo1.png
  url: https://echometerain.github.io
logo: /assets/img/echo1.png
image: /assets/img/embed.png
twitter:
  card: summary_large_image
social:
  name: echometerain
  links:
    - https://github.com/echometerain
    - https://www.youtube.com/@echometerain
google_site_verification: gnpo7dZrF7ZMbLde35E_U_AQpw00bzJJ2qSWf20gIu0
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
